/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Detection = IDL.Record({
  'letter' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'clearDetections' : IDL.Func([], [], []),
  'getDetections' : IDL.Func([], [IDL.Vec(Detection)], ['query']),
  'saveDetection' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Detection = IDL.Record({ 'letter' : IDL.Text, 'timestamp' : Time });
  
  return IDL.Service({
    'clearDetections' : IDL.Func([], [], []),
    'getDetections' : IDL.Func([], [IDL.Vec(Detection)], ['query']),
    'saveDetection' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };